version: '3'

services:
  dash:
    image: cjadkins/sb-admin-2-dash
    restart: always
    deploy:
      labels:
       - traefik.enable=true
       - traefik.port=8050
       - traefik.docker.network=traefik-public
       - traefik.frontend.rule=Host:sb-admin-2-dash.cjadkins.com
       - traefik.redirectorservice.frontend.entryPoints=http
       - traefik.redirectorservice.frontend.redirect.entryPoint=https
       # Traefik service that listens to HTTPS
       - traefik.webservice.frontend.entryPoints=https

networks:
  traefik-public:
    external: true